sudo: required
services:
  - docker
  
before_install:
  - docker build -t nicudocker2020/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nicudocker2020/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-843176447356"
  bucker_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY